name: Test based on TestPyPI installation

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install package from TestPypPI
      run: |
        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple paraqus
    - name: Run tests
      run: |
        python3 -c "import paraqus; import paraqustests as tests; tests.run_python_tests()"


